### ISSUE TITLE
Unable to connect to MQTT broker: MqttCommunicationException

### ISSUE THREAD

**Issue by MattHoneycutt** [eclipse/paho.mqtt.m2mqtt#21]
I'm getting a generic "Exception of type 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException' was thrown." while trying to connect to an MQTT broker.  I can connect to the broker just fine using MQTT.fx, and I can connect to another MQTT broker just fine using the M2MQTT libraries, so I'm thinking that the client isn't compatible with this particular broker for some reason.  

Is there some way to get additional logging details or a deeper view into what's going wrong?

**Comment by xingzhougmu** [comment]
@MattHoneycutt I have similar issue. my broker is talking over ssl. On server side (broker side) I used self-signed cert signed by self-signed CA. On client side, I install the CA cert in the trusted authority. However, I always get the generic uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException. 

> {uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException: Exception of type 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException' was thrown.
>    at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(Byte[] msgBytes, Int32 timeout)
>    at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod)
>    at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password)

The code to create the client is as below:

```
X509Certificate2 caCert = new X509Certificate2(Directory.GetCurrentDirectory() + "/Certs/Development/RootCA.crt");
                MqttClient client = new MqttClient(brokerHostName, 443, true, caCert, null, MqttSslProtocols.TLSv1_2);
string clientId = Guid.NewGuid().ToString();
client.Connect(clientId, userName, password);
```

By checking the network trace, it seems the SSL channel has been established. However, after some time (few seconds) the connection is failed with communication error.

**Comment by amguilmet** [comment]
I'm having this exact same issue, as well. I'm using Mosquitto 0.15, M2Mqtt 4.3.0 and MQTT.fx 1.5. When connecing with MQTT.fx, I can connect to mosquitto but _only_ with v3.1. If I use v3.1.1 instead, it immediately looses the connection. When connecting to mosquitto via m2mwqtt, I get the same error message in the logs as when I try MQTT.fx with v3.1.1. 

`1527514650: New connection from 127.0.0.1.

1527514650: Invalid protocol "MQTT" in CONNECT from 127.0.0.1.
1527514650: Socket read error on client (null), disconnecting.`

Before the m2mqtt client throws the MqttCommunicationException exception, it pegs the CPU out at 100% and then sometimes Mosquitto will get stuck on a connect/fail loop _event when there isn't a client trying to connect_ anymore (even when using MQTT.fx):

`1527515919: New connection from 127.0.0.1.

1527515919: Client mqttfx already connected, closing old connection.
1527515919: New client connected from 127.0.0.1 as mqttfx.
1527515920: New connection from 127.0.0.1.
1527515920: Client mqttfx already connected, closing old connection.
1527515920: New client connected from 127.0.0.1 as mqttfx.
1527515921: New connection from 127.0.0.1.
1527515921: Client mqttfx already connected, closing old connection.
1527515921: New client connected from 127.0.0.1 as mqttfx.
1527515922: New connection from 127.0.0.1.
1527515922: Client mqttfx already connected, closing old connection.
1527515922: New client connected from 127.0.0.1 as mqttfx.
1527515923: Socket read error on client mqttfx, disconnecting.`

**Comment by MatteoBaldini** [comment]
Hello, I'm also having this issue and the fix proposed by amguilmet didn't work. Does anyone have additional suggestions?

**Comment by benjamincoven** [comment]
Hello everyone, I am working on Unity for Hololens, and I am facing the same problem whatever the server is active or not. The problem only happens on Hololens and not in my desktop Unity Editor. Thank you.

**Comment by dillipdala** [comment]
Hello everyone
i am working with uPLibrary.Networking.M2Mqtt library to connect aws iot device but facing problem when try to connect    IotMqttClient.Connect("teleConnect") .

 var CaCert = X509Certificate.CreateFromCertFile(@"D:\Aws\root-CA.crt");
            X509Certificate2 clientCert = new X509Certificate2(@"D:\Aws\04d500d157.pfx","password");


            MqttClient IotMqttClient = new MqttClient(AwsEndPoint, 8883, true, CaCert, clientCert, MqttSslProtocols.TLSv1_2);
               IotMqttClient.MqttMsgPublishReceived += Client_MqttMsgPublishReceived;
               IotMqttClient.MqttMsgSubscribed += Client_MqttMsgSubscribed;
            IotMqttClient.Connect("teleConnect");


Error:
         An unhandled exception of type 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttConnectionException' occurred in M2Mqtt.Net.dll

please help me
thank you

**Comment by rusty-boffin** [comment]
I'm also getting this exception - I'm trying to connect to www.mosquitto.org (without SSL) and get the exception 35 secs after the call to .Connect(). As well as this exception, when I try to close my WPF app, the window disappears by the process remains, and I have to kill it. The debugger shows me that there's a worker thread stuck in Socket.Receive().
The interesting thing is that this doesn't always happen - sometimes the client connects OK and everything works fine. I suspect that the problem comes when I terminate my app without disconnecting the client (typically during a debugging session). Is it possible that the broker has a problem with dropped connections?

**Comment by inforaudio** [comment]
Hello 
somebody have some solution??
We test with mqttClient.ProtocolVersion = MqttProtocolVersion.Version_3_1; and nothing 

The server detect a new conection but the client cant connect 
VisualStudio show
 uPLibrary.Networking.M2Mqtt.Exceptions.MqttConnectionException: Exception connecting to the broker

**Comment by rauleteee** [comment]
@inforaudio did you find the solution? I am having the same issue

**Comment by tejswiniK** [comment]
Hello Everyone,
Facing same exception. Did anyone found solution?

**Comment by rakesh5283** [comment]
seems no one have the solution yet ?
