### ISSUE TITLE
Cannot Unsubscribe or Disconnect

### ISSUE THREAD

**Issue by devilwacause** [eclipse/paho.mqtt.m2mqtt#47]
Program needs to have the ability to unsubscribe from topics and disconnect from broker.

Method Code posted below - as well as the Client Disconnect exception thrown each time I try to disconnect.

 public void disconnectFromMQTT(List<string> Topics)
        {
            

            foreach (string t in Topics)
            {
               
                try
                {
                    myClient.Unsubscribe(new [] { t });
                }
                catch(Exception e)
                {
                    System.Windows.MessageBox.Show(Convert.ToString(e));
                }
            }
            
            try
            {
                myClient.Disconnect();
            }
            catch(Exception e)
            {
                System.Windows.MessageBox.Show(Convert.ToString(e));
            }
            
        }

Exception Thrown -

Exception thrown: 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException' in M2Mqtt.Net.dll
uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at uPLibrary.Networking.M2Mqtt.MqttNetworkChannel.Send(Byte[] buffer) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\Net\MqttNetworkChannel.cs:line 283
   at uPLibrary.Networking.M2Mqtt.MqttClient.Send(Byte[] msgBytes) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 1002
   --- End of inner exception stack trace ---
   at uPLibrary.Networking.M2Mqtt.MqttClient.Send(Byte[] msgBytes) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 1015
   at uPLibrary.Networking.M2Mqtt.MqttClient.Send(MqttMsgBase msg) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 1026
   at uPLibrary.Networking.M2Mqtt.MqttClient.Disconnect() in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 610
   at MyHomeAuto.MQTT.disconnectFromMQTT(List`1 Topics) in G:\C#\Personal Programs\MyHomeAuto\MyHomeAuto\Classes\MQTT\MQTT.cs:line 86

**Comment by FernandoMonroy** [comment]
Could you solve the issue?

**Comment by devilwacause** [comment]
> Could you solve the issue?

@FernandoMonroy - I havent touched this issue in nearly 3 years.  I will see if I still have that code base and if it is running.  Likely not however.
