### ISSUE TITLE
cannot connect to Mqtt broker on SSL

### ISSUE THREAD

**Issue by xingzhougmu** [eclipse/paho.mqtt.m2mqtt#60]
I have a MQTT broker exposing port 443, not the default 1883. I tried to connect to it with the following code, however always failed. (The code is based on .net core 1.1)

```
X509Certificate caCert = new X509Certificate(Directory.GetCurrentDirectory() + "/Certs/Production/Certificate.crt.cer");

X509Certificate clientCert = new X509Certificate(Directory.GetCurrentDirectory() + "/Certs/Production/CN_Certificate.crt.cer");

MqttClient client = new MqttClient(brokerHostName, 443, true, caCert, clientCert, MqttSslProtocols.TLSv1_2);
```

The stack trace is as below:

> at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod)
>    at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password)
>    at Test.Program.Main(String[] args) in /Users/xzhou/Projects/DysonChatbot/Test/Program.cs:line 50

By capturing the network trace, I can only see the **client hello** traffic, no **server hello** returned. But everything with the same setting works with JAVA paho MQTT client (test with MQTT.fx, where only client cert is required to set in the GUI, no server side cert is required). So, I guess there is some issue lying in this mqtt client implementation?

**Comment by xingzhougmu** [comment]
Add some network traces for this issue:

In working case (MQTT.ft):

> Secure Sockets Layer
>     **TLSv1.2** Record Layer: Handshake Protocol: Client Hello
>         Content Type: Handshake (22)
>         Version: TLS 1.2 (0x0303)
>         Length: 199
>         Handshake Protocol: Client Hello
>             Handshake Type: Client Hello (1)
>             Length: 195
>             Version: TLS 1.2 (0x0303)
>             Random
>                 **GMT Unix Time: Sep  1, 2017 13:17:47.000000000 CST**
>                 Random Bytes: 2790764721c6d7c65d1394df6ab994a77942137fe7b4b8b4...
>             **Session ID Length: 32**
>             Session ID: 5d0532fb96350b89eedd961310eb2b447e44121be8773892...
>             Cipher Suites Length: 58
>             Cipher Suites (29 suites)

While in bad case (.net core MQTT):

> Secure Sockets Layer
>     **SSL Record Layer**: Handshake Protocol: Client Hello
>         Content Type: Handshake (22)
>         Version: TLS 1.0 (0x0301)
>         Length: 332
>         Handshake Protocol: Client Hello
>             Handshake Type: Client Hello (1)
>             Length: 328
>             Version: TLS 1.2 (0x0303)
>             Random
>                 **GMT Unix Time: Oct 28, 1980 10:42:17.000000000 CST**
>                 Random Bytes: 0d8b81d595163d022229b8fa81ceba3734e9d045951f7d32...
>             **Session ID Length: 0**
>  
>             Cipher Suites Length: 202
>             Cipher Suites (101 suites)

**Comment by xingzhougmu** [comment]
the issue has been resolved by upgrading the runtime to .net core 2.0.
